defmodule Phoney.Repo.Migrations.AddUserIdToFavorite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:favorites)
    drop table (:contacts)

    create table(:favorites, primary_key: false) do
      add :contact_id, :uuid, null: false, primary_key: true
      add :user_id, :uuid, null: false, primary_key: true
    end

    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:favorites) do
      modify :contact_id,
             references(:contacts,
               column: :id,
               name: "favorites_contact_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "favorites_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:contacts) do
      add :first_name, :text
      add :last_name, :text
      add :email, :text
      add :phone_number, :text
      add :address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:contacts, [:email], name: "contacts_email_index")
  end

  def down do
    drop_if_exists unique_index(:contacts, [:email], name: "contacts_email_index")

    alter table(:contacts) do
      remove :updated_at
      remove :inserted_at
      remove :address
      remove :phone_number
      remove :email
      remove :last_name
      remove :first_name
    end

    drop constraint(:favorites, "favorites_contact_id_fkey")

    drop constraint(:favorites, "favorites_user_id_fkey")

    alter table(:favorites) do
      modify :user_id, :uuid
      modify :contact_id, :uuid
    end

    drop table(:contacts)

    drop table(:favorites)
  end
end
