defmodule Phoney.Repo.Migrations.AddPrimaryKeyToFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("favorites", "favorites_pkey")

    alter table(:favorites) do
      modify :user_id, :uuid, null: true, primary_key: false
      modify :contact_id, :uuid, null: true
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end

  def down do
    drop constraint("favorites", "favorites_pkey")

    alter table(:favorites) do
      remove :id
      modify :contact_id, :uuid, null: false
      modify :user_id, :uuid, null: false, primary_key: true
    end
  end
end
